version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/step2/zip/
    
permissions:
  - object: /home/ubuntu/app/step2/zip/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: ./deploy.sh
      timeout: 60
      runas: ubuntu
