spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  profiles:
    active: prod
    include:
      - jwt
      - oauth
      - api
      - aws
logging:
  level:
    web: debug



