spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: prod
    include:
      - jwt
      - oauth
      - api
      - aws
  cloud:
    gcp:
      project-id: my-food-project-380501
      credentials:
        location: classpath:/static/my-food-project-380501-f2649a7db984.json
logging:
  level:
    web: debug



